In [1]:
import os
import pandas as pd
import kagglehub

# Load the datasets
path1 = kagglehub.dataset_download("snehaanbhawal/resume-dataset")
path2 = kagglehub.dataset_download("ravindrasinghrana/job-description-dataset")

# List the files in dataset directory
print("files in dataset: ", os.listdir(path1))
print("files in dataset: ", os.listdir(path2))


resume_path = os.path.join(path1, 'Resume', 'Resume.csv')
job_path = os.path.join(path2, 'job_descriptions.csv')


resume_df = pd.read_csv(resume_path)
job_df = pd.read_csv(job_path)


resume_df.head(15)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/snehaanbhawal/resume-dataset?dataset_version_number=1...

100%|██████████| 62.5M/62.5M [00:00<00:00, 86.2MB/s]

Extracting files...

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/ravindrasinghrana/job-description-dataset?dataset_version_number=1...

100%|██████████| 457M/457M [00:03<00:00, 152MB/s]

Extracting files...

files in dataset:  ['data', 'Resume']
files in dataset:  ['job_descriptions.csv']

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR
5,11592605,HR GENERALIST Summary Dedic...,"<div class=""fontsize fontface vmargins hmargin...",HR
6,25824789,HR MANAGER Summary HUMAN RES...,"<div class=""fontsize fontface vmargins hmargin...",HR
7,15375009,HR MANAGER Professional Summa...,"<div class=""fontsize fontface vmargins hmargin...",HR
8,11847784,HR SPECIALIST Summary Posses...,"<div class=""fontsize fontface vmargins hmargin...",HR
9,32896934,HR CLERK Summary Translates ...,"<div class=""fontsize fontface vmargins hmargin...",HR
10,29149998,HR ASSISTANT Summary Highly ...,"<div class=""fontsize fontface vmargins hmargin...",HR
11,11480899,HR MANAGER Summary Human...,"<div class=""fontsize fontface vmargins hmargin...",HR
12,23155093,HR MANAGER Summary To obta...,"<div class=""fontsize fontface vmargins hmargin...",HR
13,11763983,HR GENERALIST Summary A peo...,"<div class=""fontsize fontface vmargins hmargin...",HR
14,27490876,HR COORDINATOR Summary App...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [2]:
job_df.head(15)

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,...,001-381-930-7517x737,Digital Marketing Specialist,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie..."
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,...,461-509-4216,Web Developer,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com..."
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525,...,9687619505,Operations Manager,Quality Control Manager,Jobs2Careers,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P..."
3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,129896,...,+1-820-643-5431x47576,Network Engineer,Wireless Network Engineer,FlexJobs,"Wireless Network Engineers design, implement, ...","{'Transportation Benefits, Professional Develo...",Wireless network design and architecture Wi-Fi...,"Design, configure, and optimize wireless netwo...",Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O..."
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,53944,...,343.975.4702x9340,Event Manager,Conference Manager,Jobs2Careers,A Conference Manager coordinates and manages c...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Event planning Conference logistics Budget man...,Specialize in conference and convention planni...,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ..."
5,116831420231957,4 to 12 Years,MCA,$59K-$93K,Brussels,Belgium,50.5039,4.4699,Full-Time,23196,...,(973)791-5355x52199,Software Tester,Quality Assurance Analyst,Snagajob,A Quality Assurance Analyst tests software and...,"{'Life and Disability Insurance, Stock Options...",Quality assurance processes Testing methodolog...,Test software applications and systems to iden...,Adani Ports and Special Economic Zone,"{""Sector"":""Infrastructure"",""Industry"":""Ports a..."
6,1292168246729889,3 to 15 Years,PhD,$63K-$103K,George Town,Cayman Islands,19.3133,-81.2546,Temporary,26119,...,001-268-510-4362x789,Teacher,Classroom Teacher,FlexJobs,A Classroom Teacher educates students in a spe...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Teaching pedagogy Classroom management Curricu...,"Plan and deliver engaging lessons, adapting te...",FedEx,"{""Sector"":""Logistics"",""Industry"":""Mail, Packag..."
7,1498778686197107,2 to 8 Years,M.Com,$65K-$102K,SÃ£o TomÃ©,Sao Tome and Principe,0.1864,6.6131,Contract,40558,...,667.202.6824x15893,UX/UI Designer,User Interface Designer,Indeed,User Interface Designers focus on the visual a...,"{'Employee Assistance Programs (EAP), Tuition ...",UI design principles and best practices Graphi...,Create visually appealing user interfaces (UI)...,Ryder System,"{""Sector"":""Transportation"",""Industry"":""Transpo..."
8,1680293940995740,2 to 9 Years,BBA,$65K-$102K,Male,Maldives,3.2028,73.2207,Temporary,105343,...,+1-337-946-9956x550,UX/UI Designer,Interaction Designer,Indeed,Interaction Designers specialize in designing ...,"{'Transportation Benefits, Professional Develo...",Interaction design principles User behavior an...,"Work on interaction design, defining how users...",Zee Entertainment Enterprises,"{""Sector"":""Media & Entertainment"",""Industry"":""..."
9,255627812588102,1 to 10 Years,BBA,$60K-$80K,Saint John's,Antigua and Barbuda,17.0608,-61.7964,Full-Time,102069,...,001-318-990-0531x978,Wedding Planner,Wedding Consultant,Stack Overflow Jobs,A Wedding Consultant assists couples in planni...,"{'Legal Assistance, Bonuses and Incentive Prog...",Wedding planning Vendor coordination Event man...,Offer expert advice and guidance to couples pl...,CSX,"{""Sector"":""Transportation"",""Industry"":""Railroa..."
10,2696958764033354,3 to 10 Years,BCA,$57K-$104K,Manama,Bahrain,26.0667,50.5577,Contract,130338,...,001-683-879-1350,QA Analyst,Performance Testing Specialist,Glassdoor,Performance Testing Specialists assess the per...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Performance testing Load testing Stress testin...,Focus on performance and load testing to asses...,McDonald's,"{""Sector"":""Food and Beverage"",""Industry"":""Food..."
11,1446194141960546,4 to 12 Years,B.Tech,$64K-$98K,The City of Hamilton,Bermuda,32.3078,-64.7505,Contract,117285,...,001-388-421-1960,Litigation Attorney,Family Law Attorney,Stack Overflow Jobs,Family Law Attorneys deal with legal matters r...,"{'Employee Referral Programs, Financial Counse...",Family law Divorce proceedings Child custody M...,"Specialize in family law matters, such as divo...",TPG Telecom,"{""Sector"":""Telecommunications"",""Industry"":""Tel..."
12,1914121205954296,3 to 15 Years,MCA,$65K-$122K,Kingston,Jamaica,18.1096,-77.2975,Part-Time,79071,...,200-851-9382,Mechanical Engineer,Mechanical Design Engineer,Stack Overflow Jobs,Mechanical Design Engineers create and develop...,"{'Tuition Reimbursement, Stock Options or Equi...","Mechanical engineering CAD software (e.g., Sol...","Design mechanical systems, components, and pro...",ThyssenKrupp AG,"{""Sector"":""Manufacturing"",""Industry"":""Industri..."
13,290761760113904,1 to 8 Years,B.Com,$56K-$86K,Banjul,Gambia,13.4432,-15.3101,Temporary,127900,...,(229)625-8850x6916,Network Administrator,Network Security Analyst,FlexJobs,Protect an organizations computer networks and...,"{'Legal Assistance, Bonuses and Incentive Prog...",Network security protocols Intrusion detection...,"Manage and secure computer networks, including...",EnLink Midstream,"{""Sector"":""Energy"",""Industry"":""Pipelines"",""Cit..."
14,1627539131873813,1 to 9 Years,MCA,$57K-$98K,Damascus,Syrian Arab Republic,34.8021,38.9968,Full-Time,92128,...,001-805-834-6153,Account Manager,Sales Account Manager,USAJOBS,A Sales Account Manager is responsible for bui...,"{'Casual Dress Code, Social and Recreational A...",Account management Sales strategy Negotiation ...,Manage sales accounts and ensure revenue growt...,NGL Energy Partners,"{""Sector"":""Energy"",""Industry"":""Pipelines"",""Cit..."

In [3]:
!pip install -U sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.2.3)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.5.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cpu)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.3.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.24.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (0.1.2)

In [4]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')

def screen_and_rank_resumes(job_index, num_resumes=50):
    job_desc = job_df.iloc[job_index]['Job Description']
    job_title = job_df.iloc[job_index]['Job Title']

    resumes_to_check = resume_df.head(num_resumes).copy()
    resume_texts = (resumes_to_check['Category'] + " " + resumes_to_check['Resume_str']).tolist()

    # Generate embeddings
    job_vector = model.encode(job_desc, convert_to_tensor=True)
    resume_vectors = model.encode(resume_texts, convert_to_tensor=True)

    # Calculate ranking scores
    scores = util.cos_sim(job_vector, resume_vectors)[0]
    resumes_to_check['Match_Score'] = scores.tolist()

    return job_title, resumes_to_check.sort_values(by='Match_Score', ascending=False)

# Run system
title, ranked_resumes = screen_and_rank_resumes(0)
print(f"Top Matches for: {title}")
print(ranked_resumes[['ID', 'Category', 'Match_Score']].head(10))

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Top Matches for: Digital Marketing Specialist
          ID Category  Match_Score
7   15375009       HR     0.342677
0   16852973       HR     0.281616
12  23155093       HR     0.277277
1   22323967       HR     0.273585
6   25824789       HR     0.271490
28  18334783       HR     0.259746
37  21265194       HR     0.240848
16  93002334       HR     0.239972
11  11480899       HR     0.238955
21  18827609       HR     0.237721

In [5]:
# Use a smaller sample to save time
sample_size = 10000
print(job_df.shape)

job_list_small = job_df['Job Description'].head(sample_size).tolist()
resume_list_small = (resume_df['Category'] + " " + resume_df['Resume_str']).head(sample_size).tolist()

# Encode with progress bar
job_embeddings = model.encode(job_list_small, convert_to_tensor=True, show_progress_bar=True)
resume_embeddings = model.encode(resume_list_small, convert_to_tensor=True, show_progress_bar=True)

(1615940, 23)

Batches:   0%|          | 0/313 [00:00<?, ?it/s]

Batches:   0%|          | 0/78 [00:00<?, ?it/s]

In [6]:
from sentence_transformers import util

# Calculate similarity scores
# Comparing the first job embedding against all resume embeddings
cosine_scores = util.cos_sim(job_embeddings[0], resume_embeddings)[0]

# Create a results dataframe for the sampled resumes
results_df = resume_df.head(len(resume_list_small)).copy()
results_df['Match_Score'] = cosine_scores.tolist()

# Rank resumes by score
ranked_resumes = results_df.sort_values(by='Match_Score', ascending=False)

# Display results
print(f"Target Job: {job_df.iloc[0]['Job Title']}")
print(ranked_resumes[['ID', 'Category', 'Match_Score']].head(10))

Target Job: Digital Marketing Specialist
            ID          Category  Match_Score
2101  75329822  PUBLIC-RELATIONS     0.687307
1619  15479281           APPAREL     0.661073
1267  11677012     DIGITAL-MEDIA     0.629623
2127  24677466  PUBLIC-RELATIONS     0.628295
1283  94492380     DIGITAL-MEDIA     0.608325
1291  59011090     DIGITAL-MEDIA     0.570114
1315  16536141     DIGITAL-MEDIA     0.560190
1285  70196518     DIGITAL-MEDIA     0.557868
2056  91197243  PUBLIC-RELATIONS     0.532524
2081  12567516  PUBLIC-RELATIONS     0.531283

In [7]:
import spacy

# Load the model
nlp = spacy.load("en_core_web_sm")

def extract_resume_info(text):
    doc = nlp(text)

    # Extracting entities
    # ORG: Companies/Schools, DATE: Tenure, PRODUCT/GPE: Tech/Locations
    entities = {
        "Organizations": list(set([ent.text for ent in doc.ents if ent.label_ == "ORG"])),
        "Experience_Timeline": list(set([ent.text for ent in doc.ents if ent.label_ == "DATE"]))
    }
    return entities

# Apply to your top 5 ranked resumes
ranked_resumes['Extracted_Info'] = ranked_resumes['Resume_str'].head(5).apply(extract_resume_info)

# Display a sample
import json
print(json.dumps(ranked_resumes.iloc[0]['Extracted_Info'], indent=2))

{
  "Organizations": [
    "Responsibilities Assisted SVP",
    "Berkeley College    Marketing        Skills",
    "Public Relations and",
    "Public Relations/Social",
    "Current     Company Name      Public Relations",
    "VMU",
    "Social Media Management",
    "Better Mornings",
    "Digital Social Media",
    "The Children's Place",
    "NBC",
    "Implemented Social Media",
    "ABC 7 News",
    "Created",
    "Communicated",
    "Scripted"
  ],
  "Experience_Timeline": [
    "2009 - 2012",
    "annually",
    "15,000+",
    "fiscal 2009 to 2012",
    "June 2005",
    "monthly"
  ]
}

In [8]:
import torch

# Save the math (embeddings)
torch.save(resume_embeddings, 'resume_embeddings.pt')

# Save the metadata (so we can map vectors back to names/IDs)
# We only need the ID and Category to keep the file small
resume_df[['ID', 'Category', 'Resume_str']].head(sample_size).to_csv('resume_metadata.csv', index=False)